//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/CameraControllers/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""88f69f69-4344-4606-a692-6215b6a148cd"",
            ""actions"": [
                {
                    ""name"": ""FirstFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""98132126-e5fa-420b-a0d9-0465b53af6a6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""04fd5db0-b2e4-40c5-b75e-895928b69bd0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondFingerContact"",
                    ""type"": ""Button"",
                    ""id"": ""17138a02-c692-44fc-bf54-e584dec9bb61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d7a97873-f009-4038-84ae-07f0a5686f58"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99fdd6d2-5ddb-4c02-9f89-f3d9775982d0"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a59921d-b66a-4db9-a759-45ae529a318e"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondFingerContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_FirstFingerPosition = m_Touch.FindAction("FirstFingerPosition", throwIfNotFound: true);
        m_Touch_SecondFingerPosition = m_Touch.FindAction("SecondFingerPosition", throwIfNotFound: true);
        m_Touch_SecondFingerContact = m_Touch.FindAction("SecondFingerContact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_FirstFingerPosition;
    private readonly InputAction m_Touch_SecondFingerPosition;
    private readonly InputAction m_Touch_SecondFingerContact;
    public struct TouchActions
    {
        private @InputActions m_Wrapper;
        public TouchActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @FirstFingerPosition => m_Wrapper.m_Touch_FirstFingerPosition;
        public InputAction @SecondFingerPosition => m_Wrapper.m_Touch_SecondFingerPosition;
        public InputAction @SecondFingerContact => m_Wrapper.m_Touch_SecondFingerContact;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @FirstFingerPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerPosition;
                @FirstFingerPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerPosition;
                @FirstFingerPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnFirstFingerPosition;
                @SecondFingerPosition.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFingerPosition.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFingerPosition.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerPosition;
                @SecondFingerContact.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerContact;
                @SecondFingerContact.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerContact;
                @SecondFingerContact.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondFingerContact;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @FirstFingerPosition.started += instance.OnFirstFingerPosition;
                @FirstFingerPosition.performed += instance.OnFirstFingerPosition;
                @FirstFingerPosition.canceled += instance.OnFirstFingerPosition;
                @SecondFingerPosition.started += instance.OnSecondFingerPosition;
                @SecondFingerPosition.performed += instance.OnSecondFingerPosition;
                @SecondFingerPosition.canceled += instance.OnSecondFingerPosition;
                @SecondFingerContact.started += instance.OnSecondFingerContact;
                @SecondFingerContact.performed += instance.OnSecondFingerContact;
                @SecondFingerContact.canceled += instance.OnSecondFingerContact;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnFirstFingerPosition(InputAction.CallbackContext context);
        void OnSecondFingerPosition(InputAction.CallbackContext context);
        void OnSecondFingerContact(InputAction.CallbackContext context);
    }
}
