//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/InputSystem/ZoomActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ZoomActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ZoomActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ZoomActions"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""bb68e835-6d71-437d-8521-cbd16989424f"",
            ""actions"": [
                {
                    ""name"": ""PrimaryFingerPos"",
                    ""type"": ""Value"",
                    ""id"": ""0366059a-d894-4a57-892b-ced9f473a53c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryFingerPos"",
                    ""type"": ""Value"",
                    ""id"": ""3676fe7d-0302-4b33-bfac-3a39c7f3418a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryTouchContact"",
                    ""type"": ""Button"",
                    ""id"": ""121798a8-2177-4ec0-9893-62eb8ce77db9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ac537f9-6468-468a-ad24-be64bf173084"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFingerPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0d585b3-f981-4854-8470-f7ebd4e87a3e"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryFingerPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4d57277-7bfc-44fd-9919-414866655f64"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_PrimaryFingerPos = m_Touch.FindAction("PrimaryFingerPos", throwIfNotFound: true);
        m_Touch_SecondaryFingerPos = m_Touch.FindAction("SecondaryFingerPos", throwIfNotFound: true);
        m_Touch_SecondaryTouchContact = m_Touch.FindAction("SecondaryTouchContact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_PrimaryFingerPos;
    private readonly InputAction m_Touch_SecondaryFingerPos;
    private readonly InputAction m_Touch_SecondaryTouchContact;
    public struct TouchActions
    {
        private @ZoomActions m_Wrapper;
        public TouchActions(@ZoomActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryFingerPos => m_Wrapper.m_Touch_PrimaryFingerPos;
        public InputAction @SecondaryFingerPos => m_Wrapper.m_Touch_SecondaryFingerPos;
        public InputAction @SecondaryTouchContact => m_Wrapper.m_Touch_SecondaryTouchContact;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @PrimaryFingerPos.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnPrimaryFingerPos;
                @PrimaryFingerPos.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnPrimaryFingerPos;
                @PrimaryFingerPos.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnPrimaryFingerPos;
                @SecondaryFingerPos.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondaryFingerPos;
                @SecondaryFingerPos.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondaryFingerPos;
                @SecondaryFingerPos.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondaryFingerPos;
                @SecondaryTouchContact.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondaryTouchContact;
                @SecondaryTouchContact.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondaryTouchContact;
                @SecondaryTouchContact.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnSecondaryTouchContact;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PrimaryFingerPos.started += instance.OnPrimaryFingerPos;
                @PrimaryFingerPos.performed += instance.OnPrimaryFingerPos;
                @PrimaryFingerPos.canceled += instance.OnPrimaryFingerPos;
                @SecondaryFingerPos.started += instance.OnSecondaryFingerPos;
                @SecondaryFingerPos.performed += instance.OnSecondaryFingerPos;
                @SecondaryFingerPos.canceled += instance.OnSecondaryFingerPos;
                @SecondaryTouchContact.started += instance.OnSecondaryTouchContact;
                @SecondaryTouchContact.performed += instance.OnSecondaryTouchContact;
                @SecondaryTouchContact.canceled += instance.OnSecondaryTouchContact;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnPrimaryFingerPos(InputAction.CallbackContext context);
        void OnSecondaryFingerPos(InputAction.CallbackContext context);
        void OnSecondaryTouchContact(InputAction.CallbackContext context);
    }
}
